name: Deploy Production

on:
  workflow_dispatch:

jobs:
  deploy:
    uses: marcel-tuinstra/devops/.github/workflows/reusable-cd-nuxt-ssg.yml@v1
    with:
      service-name: web
      image-name: ghcr.io/marcel-tuinstra/site-marcel
      health-url: https://example.com/health
      environment: production
      remote-path: /srv/site-marcel
      ssh-user: deploy
      ssh-host: production.example.com
    secrets:
      ssh-private-key: ${{ secrets.SSH_PRODUCTION_PRIVATE_KEY }}
