name: Nuxt CI (reusable)

on:
  pull_request:

jobs:
  ci:
    uses: marcel-tuinstra/devops/.github/workflows/reusable-ci.yml@v1
    with:
      node-version: "22"
      workdir: "."
      test-command: npm test
