# Template: Production CD caller workflow for Nuxt SSG sites.
# Copy this file to your consumer repo at .github/workflows/deploy-production.yml
# and replace <YOUR-...> placeholders with actual values.
#
# Required GitHub configuration in the consumer repo:
#   Environment: production (with required reviewers recommended)
#   Secrets:     SSH_PRODUCTION_PRIVATE_KEY
#   Variables:   SSH_PRODUCTION_HOST

name: Deploy Production

on:
  workflow_dispatch:

jobs:
  deploy:
    uses: marcel-tuinstra/devops/.github/workflows/reusable-cd-nuxt-ssg.yml@v1
    with:
      service-name: <YOUR-SERVICE-NAME>           # e.g. web
      image-name: ghcr.io/<YOUR-ORG>/<YOUR-REPO>  # e.g. ghcr.io/marcel-tuinstra/site-marcel
      health-url: <YOUR-PRODUCTION-HEALTH-URL>     # e.g. https://example.com/health
      environment: production
      remote-path: <YOUR-REMOTE-PATH>              # e.g. /srv/site-marcel
      ssh-user: deploy
      ssh-host: ${{ vars.SSH_PRODUCTION_HOST }}
      dockerfile: Dockerfile
    secrets:
      ssh-private-key: ${{ secrets.SSH_PRODUCTION_PRIVATE_KEY }}
